### ISSUE TITLE
Type error in result.get_counts()

### ISSUE THREAD

**Issue by ievutec** [QISKit/qiskit-tutorial#50]
I've run a couple of circuits on the 'ibmqx5' backend but realised that the optimisation of the circuit is probably making it give out the wrong amplitudes. I've attempted to fix this by adding a few barriers and ran it again but (3 times in a row) an error message came up and I narrowed it down to being solely due to the get_counts() method. Here's the error message:

Traceback (most recent call last):
  File "mbqc-simulation.py", line 232, in <module>
    plot_histogram(result.get_counts('MBQC'))
  File "/Users/TheProtonCat/anaconda/lib/python3.5/site-packages/qiskit/_quantumprogram.py", line 1300, in get_counts
    return self.get_data(name)['counts']
  File "/Users/TheProtonCat/anaconda/lib/python3.5/site-packages/qiskit/_quantumprogram.py", line 1282, in get_data
    return self.__result['result'][index]["data"]
TypeError: string indices must be integers

Since the method worked fine before I wonder if it might be the barriers that are inducing the error. I need to run this simulation for a project so any quick fix would be very much appreciated! (note that the method fails when I use it in different ways, like extracting my own values, not just when trying to plot the histogram).

**Comment by ievutec** [comment]
Note: the get_data() method seems to fail for the same reason:

Traceback (most recent call last):
  File "mbqc-simulation.py", line 194, in <module>
    counts = result.get_data('MBQC')
  File "/Users/TheProtonCat/anaconda/lib/python3.5/site-packages/qiskit/_quantumprogram.py", line 1282, in get_data
    return self.__result['result'][index]["data"]
TypeError: string indices must be integers
